# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  #name: DEFRA-COMMON-windows2019-SSV3
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Run npm install and build'

- script: |
    npm run unit-test-cov || exit 1
  displayName: 'Run Unit Tests'

- task: SonarCloudPrepare@2
  displayName: 'SonarCloudPrepare'
  inputs:
    SonarCloud: 'SC'
    organization: 'defragovuk'
    scannerMode: 'CLI'
    projectKey: 'defragovuk_Defra-APHA-CITES'
    projectName: 'Defra-APHA-CITES'
    extraProperties: |
      sonar.projectKey=defragovuk_Defra-APHA-CITES
      sonar.projectName=Defra-APHA-CITES
      sonar.sources=./
      sonar.exclusions=**/tests/**
      sonar.tests=./tests
      sonar.javascript.lcov.reportPaths=./tests/coverage/lcov.info

# sonar.testExecutionReportPaths=$(Build.SourcesDirectory)/tests/coverage/clover.xml

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'

- script: |
    git branch main
    git push https://$(GITHUB_PAT)@github.com/$REPO_NAME main
  displayName: 'Push to GitHub'