# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
  branches:
    exclude: 
    - '*'
    
pool:
  #name: DEFRA-COMMON-windows2019-SSV3
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Run npm install and build'

- script: |
    npm run unit-test-cov || exit 1
  displayName: 'Run Unit Tests'

- task: SonarCloudPrepare@2
  displayName: 'SonarCloudPrepare'
  inputs:
    SonarCloud: 'SonarCloud Github'
    organization: 'defra'
    scannerMode: 'CLI'
    projectKey: 'DEFRA_cites-pegasus'
    projectName: 'Github-Defra-APHA-CITES'
    extraProperties: |
      sonar.projectKey=DEFRA_cites-pegasus
      sonar.projectName=Github-Defra-APHA-CITES
      sonar.sources=./
      sonar.exclusions=**/tests/**
      sonar.tests=./tests
      sonar.javascript.lcov.reportPaths=./tests/coverage/lcov.info    

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
    OverWrite: true
    CleanTargetFolder: true
  displayName: 'Copy npm package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'
