# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  #name: DEFRA-COMMON-windows2019-SSV3
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'SC'
    organization: 'defragovuk'
    scannerMode: 'CLI'
    projectKey: 'defragovuk_Defra-APHA-CITES'
    projectName: 'Defra-APHA-CITES'
    extraProperties: |
      sonar.projectBaseDir=$(Build.SourcesDirectory)/sonar-cloud-ado
      sonar.projectKey=defragovuk_Defra-APHA-CITES
      sonar.organization=defragovuk
      sonar.projectName=Defra-APHA-CITES
      sonar.projectVersion=1.0
      sonar.exclusions=**/node_modules/**,coverage.html,logs/**,config/server.json,**/server/public/gft/**,**/server/public/gtm/**,**/server/public/build/**,**/public/css/**,**/gulpfile/**,**/client/sass/components/**,**/client/sass/patterns/**,**/client/sass/application-ie6.scss,**/client/sass/application-ie7.scss,**/client/sass/application-ie8.scss,**/client/sass/patterns/_check-your-answers.scss,**/client/sass/patterns/_task-list.scss,**/client/sass/core/_template.scss,**/stylesheets/**,out/**,public/javascripts/libs/**,bin/**,docs/**,**/*test.js,**/test/**
      sonar.coverage.exclusions =**/**/public/javascripts/**, **/**/**/static/**, **/gulpfile/**, **/bin/**
      sonar.host.url=https://sonarcloud.io
      sonar.javascript.lcov.reportPaths=./tests/coverage/lcov.info
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm run unit-test-cov || exit 1
  displayName: 'npm install, build and test'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy npm package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'

- script: |
    git branch main
    git push https://$(GITHUB_PAT)@github.com/$REPO_NAME main